import argparse
import difflib
import errno
import json
import os
import shlex
import subprocess
import sys
import time
from pathlib import Path
from .model import validate_config,compile_keymap,check_preserved,chord,CONTROL_NAMES,profile_of
from .transport import Device,DeviceBusy,devices
from .storage import STATE,read_files,backup,verified_write,sha
from .actions import execute

ROOT=Path(__file__).resolve().parents[2]
CONFIG=ROOT/'config/mappings.json'


def emit(value): print(json.dumps(value,ensure_ascii=False))


def load_config(path):return validate_config(json.loads(path.read_text()))


def binding_text(config):
    script=str(ROOT/'scripts/micro')
    lines=['-- Generated by Omarchy Codex Micro; edit config/mappings.json instead.']
    if config.get('quick_micro'):
        from .quick_micro import COMBO
        lines.append('o.bind('+', '.join(json.dumps(x) for x in (COMBO,'Micro: Quick Micro','omarchy-shell shell toggle fraction12.codex-micro {}'))+')')
    for number,layer in config['layers'].items():
        if layer.get('app'):
            from .routing import entries,trigger,combo
            for n,control,gesture,binding in entries(config):
                if n!=number or binding['action']['kind']=='noop':continue
                mods,key,held=trigger(config,n,control,gesture)
                command=shlex.join([script,'route',n,control,gesture,'press' if held else 'tap'])
                lines.append('o.bind('+', '.join(json.dumps(x) for x in (combo(mods,key),'Micro: '+binding['label'],command))+')')
                if held:
                    command=shlex.join([script,'route',n,control,gesture,'release'])
                    lines.append('o.bind('+', '.join(json.dumps(x) for x in (combo(mods,key),'Micro: release '+binding['label'],command))+', { release = true, locked = true })')
            continue
        for control,binding in layer['bindings'].items():
            if binding['action']['kind'] in ('keybind','key','noop'): continue
            cmd=shlex.join([script,'action',number,control])
            lines.append('o.bind('+', '.join(json.dumps(x,ensure_ascii=False) for x in (chord(int(number),control),'Micro: '+binding['label'],cmd))+')')
    return '\n'.join(lines)+'\n'


def read_status():
    """Busy is a skipped observation, never evidence of disconnection."""
    try:
        if not devices():
            return {'status':'disconnected','connected':False}
        with Device() as device:
            status=device.call('device.status')
            return {**status,'status':'connected','connected':True,'device':device.identity}
    except DeviceBusy:
        return {'status':'busy','connected':None}
    except TimeoutError as error:
        return {'status':'unresponsive','connected':None,'error':str(error)}
    except (OSError,ValueError,RuntimeError,KeyError) as error:
        if isinstance(error,OSError) and error.errno in (errno.ENOENT,errno.ENODEV):
            return {'status':'disconnected','connected':False}
        return {'status':'unavailable','connected':None,'error':str(error)}


def main():
    parser=argparse.ArgumentParser(description='Typed Codex Micro configuration for Omarchy; layer 1 is protected.')
    parser.add_argument('--config',type=Path,default=CONFIG)
    sub=parser.add_subparsers(dest='command',required=True)
    for name in ('status','validate','snapshot','plan','bindings','cheatsheet','editor-state','save-config'):sub.add_parser(name)
    p=sub.add_parser('apply');p.add_argument('--expected-sha256',required=True)
    p=sub.add_parser('restore');p.add_argument('backup',type=Path);p.add_argument('--expected-sha256',required=True)
    p=sub.add_parser('action');p.add_argument('layer',choices=['2','3']);p.add_argument('control',choices=CONTROL_NAMES);p.add_argument('--dry-run',action='store_true')
    sub.add_parser('init')
    sub.add_parser('dispatch-server')
    p=sub.add_parser('route');p.add_argument('layer',choices=['2','3']);p.add_argument('control',choices=CONTROL_NAMES);p.add_argument('gesture',choices=['single','double','tap_hold']);p.add_argument('phase',choices=['tap','press','release'])
    args=parser.parse_args()
    try:
        if args.command=='init':
            from .configuration import initialize
            return emit({'created':initialize(args.config,ROOT/'config/defaults.json'),'config':str(args.config)})
        if args.command=='dispatch-server':
            from .app_dispatch import serve
            return serve(args.config)
        if args.command=='route':
            from .app_dispatch import send
            return send(args.layer,args.control,args.gesture,args.phase)
        if args.command=='editor-state':
            from .editor import editor_state
            return emit(editor_state(args.config))
        if args.command=='save-config':
            from .editor import save_config
            return emit(save_config(args.config,json.loads(sys.stdin.readline())))
        if args.command=='status':return emit(read_status())
        config=load_config(args.config)
        if args.command=='validate':return emit({'valid':True,'layers':[2,3],'profile':config['profile']})
        if args.command=='bindings':return print(binding_text(config),end='')
        if args.command=='cheatsheet':
            for layer,data in config['layers'].items():
                print(f'\nLayer {layer}: {data["name"]}')
                for control,b in data['bindings'].items():print(f'  {control:12} {b["label"]}')
            return
        if args.command=='action':
            b=config['layers'][args.layer]['bindings'].get(args.control)
            if not b:raise ValueError('Control is not mapped')
            if args.dry_run:return emit(b)
            # Disable/uninstall the plugin without leaving active hotkeys behind.
            shell_config=Path.home()/'.config/omarchy/shell.json'
            settings=json.loads(shell_config.read_text())
            plugin='fraction12.codex-micro'
            entries=list(settings.get('plugins',[]))
            for section in settings.get('bar',{}).get('layout',{}).values():
                if isinstance(section,list):entries.extend(section)
            enabled=any((entry.get('id') if isinstance(entry,dict) else entry)==plugin for entry in entries)
            if not enabled or plugin in settings.get('disabledPlugins',[]):
                raise ValueError('Codex Micro plugin is disabled')
            result=execute(b['action'])
            STATE.mkdir(parents=True,exist_ok=True,mode=0o700)
            record={'time':time.time(),'layer':int(args.layer),'control':args.control,'label':b['label'],'dispatched':True}
            temp=STATE/f'.last-action-{os.getpid()}.json'
            temp.write_text(json.dumps(record)+'\n');temp.chmod(0o600);temp.replace(STATE/'last-action.json')
            return emit(result)
        with Device() as d:
            status=d.call('device.status')
            current=read_files(d)
            if args.command=='snapshot':return emit({'backup':str(backup(d,status,current)), 'sha256':sha(current['keymap.json'])})
            original=json.loads(current['keymap.json'])
            if args.command=='restore':
                manifest=json.loads((args.backup/'manifest.json').read_text())
                if manifest['identity']['serial']!=d.identity['serial']:raise ValueError('Backup belongs to another device')
                candidate=(args.backup/'keymap.json').read_bytes()
                if sha(candidate)!=manifest['sha256']['keymap.json']:raise ValueError('Backup checksum mismatch')
                target=json.loads(candidate)
                # Restore may remove our generated macros, but may never alter Codex or other profiles.
                check_preserved(target,original,config['profile'])
            else:
                target=compile_keymap(original,config)
                candidate=json.dumps(target,separators=(',',':'),ensure_ascii=False).encode()
            if args.command=='plan':
                diff=list(difflib.unified_diff(json.dumps(original,indent=2).splitlines(),json.dumps(target,indent=2).splitlines(),fromfile='device',tofile='candidate'))
                return emit({'sha256':sha(current['keymap.json']),'candidate_sha256':sha(candidate),'profile':config['profile'],'layers':[2,3],'layer1_preserved':True,'changed':original!=target,'diff':diff})
            if status.get('version')!='0.6.2':raise ValueError('Writes are supported only for verified firmware 0.6.2')
            if sha(current['keymap.json'])!=args.expected_sha256:raise ValueError('Stale expected revision; rerun plan')
            if original==target:return emit({'changed':False,'sha256':sha(current['keymap.json'])})
            destination=backup(d,status,current)
            emit({'backup':str(destination),'phase':'backed-up'});sys.stdout.flush()
            after=verified_write(d,current,candidate)
            emit({'changed':True,'sha256':sha(after['keymap.json']),'backup':str(destination),'layer1_preserved':True})
    except (OSError,ValueError,RuntimeError,KeyError) as error:
        emit({'error':str(error),'connected':False} if args.command=='status' else {'error':str(error)})
        sys.exit(1)
