"""Recoverable host integration; never touches device mappings."""
from contextlib import contextmanager
import os
import subprocess
import time
import uuid
from .editor import atomic_write


def owned_files(link,root,generated):
    if (link.exists() or link.is_symlink()) and (not link.is_symlink() or link.resolve()!=root):
        raise SystemExit('Installed plugin path does not belong to this checkout')
    if generated.exists() and not generated.read_text().startswith('-- Generated by Omarchy Codex Micro;'):
        raise SystemExit('Generated file was replaced; leaving host integration unchanged')


def reload_hyprland():
    subprocess.run(['hyprctl','reload'],check=True,capture_output=True)
    errors=subprocess.check_output(['hyprctl','configerrors'],text=True).strip()
    if errors:raise RuntimeError('Hyprland rejected configuration: '+errors)


@contextmanager
def transaction(paths,link,state):
    snapshots={p:(p.read_bytes(),p.stat().st_mode & 0o777) if p.exists() else None for p in paths}
    link_target=os.readlink(link) if link.is_symlink() else None
    backup=state/'host-backups'/(time.strftime('%Y%m%dT%H%M%S')+'-'+uuid.uuid4().hex[:8])
    backup.mkdir(parents=True,mode=0o700)
    for p,data in snapshots.items():
        if data is not None:
            dest=backup/p.name;dest.write_bytes(data[0]);dest.chmod(0o600)
    try:yield backup
    except BaseException as error:
        failures=[]
        for p,data in snapshots.items():
            try:
                if data is None:p.unlink(missing_ok=True)
                else:
                    atomic_write(p,data[0]);p.chmod(data[1])
            except OSError as failure:failures.append(str(failure))
        try:
            if link.is_symlink():link.unlink()
            if link_target is not None:link.symlink_to(link_target,target_is_directory=True)
        except OSError as failure:failures.append(str(failure))
        try:
            reload_hyprland()
            subprocess.run(['omarchy-shell','shell','rescanPlugins'],check=True,capture_output=True)
        except (OSError,RuntimeError,subprocess.SubprocessError) as failure:failures.append(str(failure))
        if failures:raise RuntimeError(f'{error}; recovery needs attention: {failures}; backup: {backup}') from error
        raise
